# Generated by Django 5.2.6 on 2026-01-23 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_enquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'permissions': [('View_enquiry', 'Can view enquiry'), ('Delete_enquiry', 'Can delete enquiry')]},
        ),
    ]
