# Generated by Django 5.2.6 on 2026-02-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_enquiry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={},
        ),
    ]
