# Generated by Django 5.2.6 on 2026-02-08 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_enquiry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='quantity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
