# Generated by Django 5.2.6 on 2026-02-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='source',
            field=models.CharField(choices=[('contact', 'Contact Page'), ('product', 'Product Enquiry'), ('whatsapp', 'WhatsApp'), ('manual', 'Manual Entry')], default='contact', max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
