# Generated by Django 5.2.6 on 2026-02-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_enquiry_follow_up_date_enquiry_notes_enquiry_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at']},
        ),
    ]
