# Generated by Django 5.2.6 on 2026-02-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_enquiry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Sales person name', max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('negotiation', 'Negotiation'), ('converted', 'Converted'), ('closed', 'Closed'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
