# Generated by Django 5.1.5 on 2026-02-23 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_customer_supplier_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., Material, Head Style, Power', max_length=100)),
                ('value', models.CharField(help_text='e.g., Hardened Steel, Flat Head, 500W', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='shop.product')),
            ],
        ),
    ]
